# Generated by Django 6.0.4 on 2026-04-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('bg_color', models.CharField(max_length=50)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_item_name_per_cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='add_ons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sugar_level',
            field=models.CharField(default='100%', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='add_ons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sugar_level',
            field=models.CharField(default='100%', max_length=20),
        ),
    ]
