# Generated by Django 6.0.4 on 2026-04-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_menuitem_and_more'),
        ('accounts', '0005_order_fulfillment_fields'),
    ]

    operations = [
    ]
