# Generated by Django 4.2.27 on 2026-04-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cartitem_notes_orderitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Available inventory count. 0 = unlimited if track_stock is False.'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='track_stock',
            field=models.BooleanField(default=False, help_text='Enable inventory tracking for this item'),
        ),
        migrations.AddField(
            model_name='order',
            name='void_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
