# Generated by Django 6.0.4 on 2026-04-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_order_pickup_time_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 to 5 stars', null=True),
        ),
    ]
