# Generated by Django 6.0.4 on 2026-05-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_order_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Drink photo. Falls back to color-based webp if not set.', null=True, upload_to='menu_images/'),
        ),
    ]
