# Generated by Django 4.2.27 on 2026-05-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived orders are hidden from the main admin view'),
        ),
    ]
