# Generated by Django 4.2.27 on 2026-05-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_order_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short bio or notes about this staff member'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, default='', help_text='Job title / position (e.g. Barista, Shift Manager)', max_length=50),
        ),
    ]
