# Generated by Django 4.2.27 on 2026-05-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_phone_position_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived staff are hidden from scheduling but can still log in'),
        ),
    ]
