# Generated by Django 4.2.27 on 2026-05-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_archived',
        ),
    ]
