# Generated by Django 4.2.27 on 2026-05-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_customuser_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, choices=[('barista', 'Barista'), ('cashier', 'Cashier'), ('manager', 'Manager'), ('delivery', 'Delivery'), ('cleaner', 'Cleaner')], default='', help_text='Staff role / position', max_length=20),
        ),
    ]
