# Generated by Django 4.2.27 on 2026-05-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_position_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Auto-generated employee ID (e.g. SPY-0001)', max_length=10, null=True, unique=True),
        ),
    ]
