# Generated by Django 4.2.27 on 2026-05-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Staff profile photo', null=True, upload_to='avatars/'),
        ),
    ]
