# Generated by Django 4.2.27 on 2026-05-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_shiftlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftlog',
            name='break_end',
            field=models.DateTimeField(blank=True, help_text='Timestamp when break ended', null=True),
        ),
        migrations.AddField(
            model_name='shiftlog',
            name='break_start',
            field=models.DateTimeField(blank=True, help_text='Timestamp when break started', null=True),
        ),
    ]
