# Generated by Django 4.2.27 on 2026-05-03 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_shiftlog_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftlog',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When admin approved this clock-in', null=True),
        ),
        migrations.AddField(
            model_name='shiftlog',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this clock-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftlog',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether admin approved this clock-in'),
        ),
        migrations.AddField(
            model_name='shiftlog',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When admin rejected this clock-in', null=True),
        ),
    ]
