# Generated by Django 4.2.27 on 2026-05-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_shiftlog_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftlog',
            name='rejected_at',
        ),
        migrations.AddField(
            model_name='shiftlog',
            name='attendance_mark',
            field=models.CharField(blank=True, choices=[('on_time', 'On Time'), ('late', 'Late'), ('absent', 'Absent')], help_text='Admin mark: on_time, late, or absent', max_length=10, null=True),
        ),
    ]
