# Generated by Django 4.2.27 on 2026-05-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_shiftlog_attendance_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled pickup datetime for auto-cancel logic', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(blank=True, help_text='Scheduled pickup time (display)', max_length=50, null=True),
        ),
    ]
