# Generated by Django 4.2.27 on 2026-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_order_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shift_start',
            field=models.TimeField(blank=True, help_text='Scheduled shift start time (e.g. 08:00)', null=True),
        ),
        migrations.AddField(
            model_name='shiftlog',
            name='minutes_late',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes past shift start time when clocked in', null=True),
        ),
    ]
