# Generated by Django 4.2.27 on 2026-05-03 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_late_arrival_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shift_end',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), help_text='Scheduled shift end time (default: 5:00 PM)', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shift_start',
            field=models.TimeField(blank=True, default=datetime.time(7, 30), help_text='Scheduled shift start time (default: 7:30 AM)', null=True),
        ),
    ]
