# Generated by Django 4.2.27 on 2026-05-03 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_shift_end_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('clock_in', 'Clocked In'), ('clock_out', 'Clocked Out'), ('break_start', 'Break Started'), ('break_end', 'Break Ended'), ('approved', 'Approved (On Time)'), ('marked_late', 'Marked Late'), ('marked_absent', 'Marked Absent'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('order_voided', 'Order Voided')], max_length=20)),
                ('description', models.CharField(help_text='Human-readable description of the action', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='accounts.order')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Admin who performed the action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL)),
                ('shift_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='accounts.shiftlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'staff activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
