# Generated by Django 4.2.27 on 2026-07-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_menuitem_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderstatuslog',
            new_name='accounts_or_order_i_11d7c9_idx',
            old_name='accounts_or_order_i_6d0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='orderstatuslog',
            new_name='accounts_or_status_163a3c_idx',
            old_name='accounts_or_status__f8e2a1_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('maya', 'Maya'), ('card', 'Card')], default='', help_text='How the customer will pay', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', help_text='Payment settlement status', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Menu item photo. Falls back to category placeholder if not set.', null=True, upload_to='menu_images/'),
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='action',
            field=models.CharField(choices=[('clock_in', 'Clocked In'), ('clock_out', 'Clocked Out'), ('break_start', 'Break Started'), ('break_end', 'Break Ended'), ('approved', 'Approved (On Time)'), ('marked_late', 'Marked Late'), ('marked_absent', 'Marked Absent'), ('planned_absence', 'Planned Absence Logged'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('order_voided', 'Order Voided')], max_length=20),
        ),
    ]
