# Generated by Django 4.2.27 on 2026-07-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_order_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('gotyme', 'GoTyme'), ('card', 'Card')], default='', help_text='How the customer will pay', max_length=20),
        ),
    ]
