# Generated by Django 6.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_cafe_shift_hours_730_to_2030"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image_data",
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image_content_type",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
